version: "3.8"

services:

  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build: ./api
    command: rails s -p 3000 -b '0.0.0.0'
    environment: 
      - DATABASE_PASSWORD=password
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build: ./client
    command: sh -c "yarn install && yarn dev"
    ports: 
      - 8080:8080
    volumes: 
      - ./client:client
      - ./node_modules:/client/node_modules

volumes: 
  db:
  node_modules: